name: tfmodel
description: A Flutter package for showing Transfer Function properly.
version: 0.0.2
homepage: https://github.com/stelselim/tfmodel_flutter_package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
